#!/usr/bin/env python3
"""
Generate ESP8266 partition table CSV for client/server apps.

The generator produces a partitions CSV that uses the entire remaining flash
for the SPIFFS data partition. The factory (app) partition is sized to the
actual .bin file plus a small margin.

Usage:
  generate_partitions.py --app <client|server> --sdkconfig <path> \
                        --app-bin <path> [--margin-bytes N] \
                        --output <path>

If --app-bin is omitted (or the file does not exist), the generator falls
back to a 1 MB factory partition, which is the size used in the initial
"first pass" of the two-pass build. After the first pass, the real .bin
file exists and the second pass produces the tight partition table.

Flash size is read from CONFIG_ESPTOOLPY_FLASHSIZE in sdkconfig.
"""

import argparse
import os
import re
import sys

APP_OFFSET = 0x10000
NVS_OFFSET = 0x9000
NVS_SIZE = 0x4000
PHY_OFFSET = 0xf000
PHY_SIZE = 0x1000
DEFAULT_FACTORY_SIZE = 0x100000  # 1 MB initial fallback
PARTITION_ALIGN = 0x1000  # 4 KB
DEFAULT_MARGIN = 128 * 1024  # 128 KB


def read_flash_size(sdkconfig_path):
    """Return flash size in bytes from sdkconfig."""
    if not os.path.isfile(sdkconfig_path):
        die(f"sdkconfig not found: {sdkconfig_path}")
    size_map = {
        "CONFIG_ESPTOOLPY_FLASHSIZE_1MB": 0x100000,
        "CONFIG_ESPTOOLPY_FLASHSIZE_2MB": 0x200000,
        "CONFIG_ESPTOOLPY_FLASHSIZE_4MB": 0x400000,
        "CONFIG_ESPTOOLPY_FLASHSIZE_8MB": 0x800000,
        "CONFIG_ESPTOOLPY_FLASHSIZE_16MB": 0x1000000,
    }
    with open(sdkconfig_path, "r") as f:
        for line in f:
            line = line.strip()
            for key, size in size_map.items():
                if line.startswith(f"{key}=y"):
                    return size
    die(f"Could not determine flash size from {sdkconfig_path}")


def align_up(value, align):
    return (value + align - 1) // align * align


def die(msg):
    print(f"generate_partitions: {msg}", file=sys.stderr)
    sys.exit(1)


def format_size(size):
    return f"0x{size:x}"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--app", required=True, choices=["client", "server"])
    p.add_argument("--sdkconfig", required=True)
    p.add_argument("--app-bin", default=None)
    p.add_argument("--margin-bytes", type=int, default=DEFAULT_MARGIN)
    p.add_argument("--output", required=True)
    args = p.parse_args()

    flash_size = read_flash_size(args.sdkconfig)

    factory_size = DEFAULT_FACTORY_SIZE
    used_bin = False
    if args.app_bin and os.path.isfile(args.app_bin):
        bin_size = os.path.getsize(args.app_bin)
        factory_size = align_up(bin_size, PARTITION_ALIGN) + args.margin_bytes
        used_bin = True
        if bin_size == 0:
            die(f"app bin is empty: {args.app_bin}")

    storage_offset = APP_OFFSET + factory_size
    if storage_offset >= flash_size:
        die(
            f"factory partition (0x{factory_size:x}) does not fit into flash "
            f"(0x{flash_size:x}). Reduce --margin-bytes."
        )

    storage_size = flash_size - storage_offset

    storage_name = "storage"
    output = f"""# Name,   Type, SubType, Offset,   Size, Flags
# Auto-generated by cmake/generate_partitions.py
# Flash size: {format_size(flash_size)}
# App bin: {args.app_bin if used_bin else "none (first pass, using 1MB fallback)"}
# Factory margin: {args.margin_bytes} bytes
nvs,      data, nvs,     0x9000,   0x4000,
phy_init, data, phy,     0xf000,   0x1000,
factory,  app,  factory, 0x10000,  {format_size(factory_size)},
{storage_name},  data, spiffs,  {format_size(storage_offset)}, {format_size(storage_size)},
"""

    with open(args.output, "w") as f:
        f.write(output)

    print(
        f"generate_partitions: flash=0x{flash_size:x} "
        f"factory=0x{factory_size:x} (bin={'yes' if used_bin else 'no'}) "
        f"storage=0x{storage_offset:x}+0x{storage_size:x} "
        f"({storage_size / 1024:.1f} KB) -> {args.output}"
    )


if __name__ == "__main__":
    main()
